name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  # Auto-merge Dependabot PRs for minor/patch updates
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile

    - name: Run backend tests
      working-directory: ./backend
      env:
        DATABASE_URL: sqlite:///./test.db
      run: |
        python -m pytest -v --tb=short

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        yarn test --watchAll=false

    - name: Auto-merge PR
      uses: fastify/github-action-merge-dependabot@v4
      with:
        target: minor
        github-token: ${{ secrets.GITHUB_TOKEN }}

  # Security updates auto-merge
  security-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.title, 'security')

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install backend dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install frontend dependencies
      working-directory: ./frontend
      run: yarn install --frozen-lockfile

    - name: Run backend tests
      working-directory: ./backend
      env:
        DATABASE_URL: sqlite:///./test.db
      run: |
        python -m pytest -v --tb=short

    - name: Run frontend tests
      working-directory: ./frontend
      run: |
        yarn test --watchAll=false

    - name: Auto-merge security PR
      uses: fastify/github-action-merge-dependabot@v4
      with:
        target: patch
        github-token: ${{ secrets.GITHUB_TOKEN }}
